name: Android CI

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Config NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip
        unzip -q android-ndk-r20b-linux-x86_64.zip
        echo ANDROID_NDK_HOME:$ANDROID_NDK_HOME
        touch local.properties
        echo "ndk.dir=$(pwd)/android-ndk-r20b" >> local.properties
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        cat local.properties
        ./gradlew :app:assembleDebug
      
    - name: Upload Release Assets
      uses: alexellis/upload-assets@0.3.0
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["app/build/outputs/apk/debug/app-debug.apk"]'
